---
title: "R Practice: Functions"
format: html
---

### Question 1 Function that doubles any number

```{r}
double <- function(number) {
  number_doubled <- number * 2
  return(number_doubled)
}

double(5)
```
### Question 2 Function that displays age
```{r}
exclaim_age <- function(age) {
  return(paste("I am", age, "years old!"))
}

exclaim_age(11)
```

### Questsion 3 functions with conditionals
```{r}
# "find_max() function" #
find_max <- function(value_1, value_2) {
    if(is.numeric(value_1) == FALSE | is.numeric(value_2) == FALSE) stop('Value must be a number')
    if (value_1 > value_2) {
        return(value_1)
    }
    else if (value_2 > value_1) {
        return(value_2)
    }
} 

find_max(1, c)
find_max(2,1)

find_max(2,1) * 2
```
```{r}
# "find_max() function" #
find_max <- function(value_1, value_2) {
  if((value_1) == (value_2)) stop("values cannot be equal")
    
    if (value_1 > value_2) {
        return(value_1)
    }
    else if (value_2 > value_1) {
        return(value_2)
    }
}

find_max(4, 4)
```

### Question 4D
```{r}
find_max <- function(value_1, value_2) {
  if((value_1) == (value_2)) {
    return(paste("shared value is", value_1))
  }
    
    if (value_1 > value_2) {
        return(value_1)
    }
    else if (value_2 > value_1) {
        return(value_2)
    }
}

find_max(4, 4)

```

